let disruptedStationsJSON = #"""
[
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUKSH",
        "fromDate": "2023-06-26T03:30:00Z",
        "toDate": "2024-06-24T00:29:00Z",
        "description": "KENTISH TOWN UNDERGROUND STATION: The station will close from Monday 26 June for up to a year to enable vital work to be carried out to replace the escalators. Kentish Town Thameslink station will remain open for customers to use while the escalator replacement works are taking place. Nearby Tufnell Park Tube station is accessible by using the extensive local bus network or from Kentish Town station on foot (11 minutes). There is no major work planned on these alternative routes during the closure of the Tube station.",
        "commonName": "Kentish Town Underground Station",
        "type": "Closure",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUKSH",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLULNB",
        "fromDate": "2018-01-22T11:40:00Z",
        "toDate": "2025-12-30T01:29:00Z",
        "description": "LONDON BRIDGE STATION: Please note that step free interchange between the Jubilee and Northern lines is partly at street level, in both directions. Lifts are available between Northern line and Borough High Street entrance then via Borough High Street, St Thomas Street and Joiner Street to the main Underground ticket hall from where lifts are available to/from the Jubilee line.",
        "commonName": "London Bridge Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLULNB",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GCNDAW",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "CANADA WATER STATION: This station has short London Overground platforms. Customers are advised to travel in the front 4 coaches and listen to on-board announcements.",
        "commonName": "Canada Water Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GCNDAW",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GRTHERHI",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "ROTHERHITHE STATION: This station has short platforms. Customers are advised to travel in the front 4 coaches and listen to on-board announcements.",
        "commonName": "Rotherhithe Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GRTHERHI",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLULVT",
        "fromDate": "2023-09-11T03:30:00Z",
        "toDate": "2024-12-01T01:29:00Z",
        "description": "LIVERPOOL STREET UNDERGROUND STATION: From Monday 11 September until autumn 2024, there is a reduced escalator service to/from the Central line platforms. The bank of three escalators at the front end of the eastbound/rear end of the westbound platforms will be out of service while they are replaced. Please use alternative escalators at the other end of the platforms to exit and interchange",
        "commonName": "Liverpool Street Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLULVT",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GSYDENHM",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "SYDENHAM STATION: This station has short platforms. Customers are advised to travel in the front 8 coaches and listen to on-board announcements.",
        "commonName": "Sydenham Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GSYDENHM",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GMRYLAND",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "MARYLAND STATION: This station has short platforms for Elizabeth line services. Customers are advised to travel in the front 7 coaches and listen to on-board announcements. Customers with buggies should travel in the front 4 coaches.",
        "commonName": "Maryland Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GMRYLAND",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GFRSTGT",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "FOREST GATE STATION: This station has short platforms for Elizabeth line services. Customers are advised to travel in the front 7 coaches and listen to on-board announcements. Customers with buggies should travel in the front 4 coaches.",
        "commonName": "Forest Gate Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GFRSTGT",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GMANRPK",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "MANOR PARK STATION: This station has short platforms for Elizabeth line services. Customers are advised to travel in the front 7 coaches and listen to on-board announcements. Customers with buggies should travel in the front 4 coaches.",
        "commonName": "Manor Park Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GMANRPK",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GBNHAM",
        "fromDate": "2022-10-14T14:12:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "BURNHAM STATION: The doors of the ninth carriage will not open at Burnham station. Please travel in the front eight carriages. Customers with buggies should travel in the front four carriages.",
        "commonName": "Burnham (Berks) Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GBNHAM",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GIVER",
        "fromDate": "2022-10-14T14:12:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "IVER STATION: The doors of the ninth carriage will not open at Iver station. Please travel in the front eight carriages. Customers with buggies should travel in the front four carriages.",
        "commonName": "Iver Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GIVER",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GTAPLOW",
        "fromDate": "2022-10-14T14:12:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "TAPLOW STATION: The doors of the ninth carriage will not open at Taplow station. Please travel in the front eight carriages. Customers with buggies should travel in the front four carriages.",
        "commonName": "Taplow Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GTAPLOW",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GMDNHEAD",
        "fromDate": "2022-10-14T14:12:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "MAIDENHEAD STATION: The doors of the ninth carriage, and last doors of the eighth carriage, will not open at Maidenhead station. Please travel in the front seven carriages. Customers with buggies should travel in the front four carriages.",
        "commonName": "Maidenhead Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GMDNHEAD",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GTWYFORD",
        "fromDate": "2022-10-14T14:12:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "TWYFORD STATION: The doors of the ninth carriage, and last doors of the eighth carriage, will not open at Twyford station. Please travel in the front seven carriages. Customers with buggies should travel in the front four carriages.",
        "commonName": "Twyford Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GTWYFORD",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHANWELL",
        "fromDate": "2022-10-14T14:12:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "HANWELL STATION: The doors of the eighth and ninth carriages, and middle and rear doors of the seventh carriage, will not open at Hanwell station. Please travel in the front six carriages. Customers with buggies should travel in the front four carriages.",
        "commonName": "Hanwell Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GHANWELL",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUWLO",
        "fromDate": "2023-01-10T13:44:00Z",
        "toDate": "2024-03-31T00:29:00Z",
        "description": "WATERLOO STATION: The southbound Bakerloo line platform is step free to/from street level. Please note that due to the curve of the platform, the gap between platform and train exceeds the size that any boarding ramp can be safely used",
        "commonName": "Waterloo Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUWLO",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUHWT",
        "fromDate": "2023-01-24T13:54:00Z",
        "toDate": "2024-11-24T01:29:00Z",
        "description": "HOUNSLOW WEST STATION: Entrance and exit via stairlift for manual wheelchair users only. The maximum operating weight of the stairlift is 225kg.",
        "commonName": "Hounslow West Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUHWT",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GSVNKNGS",
        "fromDate": "2021-04-08T08:32:00Z",
        "toDate": "2024-11-30T01:29:00Z",
        "description": "SEVEN KINGS STATION: This station has short platforms for Elizabeth line services. Customers are advised to travel in the front 7 coaches and listen to on-board announcements. Customers with buggies should travel in the front 4 coaches.",
        "commonName": "Seven Kings Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GSVNKNGS",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GPADTLL",
        "fromDate": "2023-04-03T12:11:00Z",
        "toDate": "2024-04-04T00:29:00Z",
        "description": "Elizabeth line platforms A & B can be accessed by exiting London Paddington National Rail station via the exit next to platform 1 and entering Paddington Elizabeth line station by the adjacent escalators or lifts.",
        "commonName": "Paddington",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GPADTLL",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUHWY",
        "fromDate": "2023-05-09T03:30:00Z",
        "toDate": "2024-10-01T00:29:00Z",
        "description": "HOLLOWAY ROAD STATION: From Tuesday 9 May until September 2024: Reduced lift service at Holloway Road until mid-July, queuing likely during peaks. Please consider using Arsenal or Caledonian Road stations. During Emirates Stadium events, Holloway Road will be closed for two hours before the start of the event and will open 15 minutes after the start of the event. During return traffic the station will be closed 15 minutes before the end of the event and will be kept closed for 90 minutes after the event. These adjustments may be subject to alteration/",
        "commonName": "Holloway Road Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUHWY",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHAKNYNM",
        "fromDate": "2023-06-22T10:39:00Z",
        "toDate": "2024-09-29T00:29:00Z",
        "description": "HACKNEY DOWNS STATION: Step-free access to platform 1 (served by Chingford to Liverpool Street and southbound Greater Anglia trains via Tottenham Hale) is available but only via the interchange and lift link to/from Hackney Central station. Please enter and exit via this route. Step-free access is not available to/from other platforms or to/from the main entrance at Hackney Downs.",
        "commonName": "Hackney Downs Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GHAKNYNM",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLULVT",
        "fromDate": "2023-09-11T03:30:00Z",
        "toDate": "2024-12-01T01:29:00Z",
        "description": "LIVERPOOL STREET UNDERGROUND STATION: From Monday 11 September until autumn 2024, there is a reduced escalator service to/from the Central line platforms. The bank of three escalators at the front end of the eastbound/rear end of the westbound platforms will be out of service while they are replaced.\r\n\r\nPlease use alternative escalators at the other end of the platforms to exit and interchange",
        "commonName": "Liverpool Street Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLULVT",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLULNB",
        "fromDate": "2023-09-04T15:44:00Z",
        "toDate": "2024-04-01T00:29:00Z",
        "description": "LONDON BRIDGE UNDERGROUND STATION: Until March 2024, a reduced escalator service to the Jubilee line and one-way system in operation. Follow directional posters and staff instructions",
        "commonName": "London Bridge Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLULNB",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUSWK",
        "fromDate": "2023-09-30T03:30:00Z",
        "toDate": "2023-12-30T01:29:00Z",
        "description": "Southwark station ticket machines do not currently accept cash. Please top up your Oyster or buy tickets using debit or credit cards. You can also top up with the TfL Oyster app. Contactless can also be used to pay at the gates. If you need to use cash, you can top up at Local Express, 202-206 Unit 2, Union Street, SE1 0LX 165m from the main entrance (Oyster top up available between 0430 and 2344). Alternatively, use ticket machines at nearby London Underground stations that accept cash, which includes nearby Waterloo station.",
        "commonName": "Southwark Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUSWK",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUFPK",
        "fromDate": "2023-09-27T16:27:00Z",
        "toDate": "2024-02-29T01:29:00Z",
        "description": "FINSBURY PARK STATION: The Seven Sisters Road entrance is open Monday to Friday between 0700 and 1900 and is usually closed at weekends. Please use the Station Place entrance instead.",
        "commonName": "Finsbury Park Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUFPK",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GMDNHEAD",
        "fromDate": "2023-11-06T04:30:00Z",
        "toDate": "2024-09-01T00:29:00Z",
        "description": "MAIDENHEAD STATION: From Monday 6 November until August 2024, no step-free access between street level and platforms 2 and 3. This will affect westbound Elizabeth line and GWR services as well as some eastbound services during service disruption and engineering works. Marlow services would not be affected at any time.",
        "commonName": "Maidenhead Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GMDNHEAD",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZNEUGST",
        "fromDate": "2023-11-15T15:23:00Z",
        "toDate": "2024-12-23T01:29:00Z",
        "description": "NINE ELMS STATION: For northbound step-free access journeys from Nine Elms, please use the marked boarding point adjacent to the fifth carriage.",
        "commonName": "Nine Elms Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZNEUGST",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GSURREYQ",
        "fromDate": "2023-11-16T11:11:00Z",
        "toDate": "2025-11-30T01:29:00Z",
        "description": "Surrey Quays station: The doors on the last carriage of trains on the southbound platform will not open due to station improvement work. Please use the front four carriages of the train to board or alight trains.",
        "commonName": "Surrey Quays Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GSURREYQ",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUBST",
        "fromDate": "2023-12-05T04:30:00Z",
        "toDate": "2023-12-23T01:29:00Z",
        "description": "BAKER STREET STATION: From Tuesday 5 until Friday 22 December, the North entrance in Baker Street (by Boots) will be closed due to structural works taking place. Please use the main entrance in Marylebone Road.",
        "commonName": "Baker Street Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUBST",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLCUT",
        "fromDate": "2023-05-22T12:31:00Z",
        "toDate": "2023-12-31T01:29:00Z",
        "description": "CUTTY SARK FOR MARITIME GREENWICH: Reduced escalator service. Access to the station is currently via stairs with limited step-free lift access.",
        "commonName": "Cutty Sark (for Maritime Greenwich) DLR Station",
        "type": "Interchange Message",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLCUT",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLCUT",
        "fromDate": "2023-05-22T12:29:00Z",
        "toDate": "2023-12-31T01:29:00Z",
        "description": "CUTTY SARK FOR MARITIME GREENWICH: Reduced escalator service. Access to the station is currently via stairs with limited step-free lift access.",
        "commonName": "Cutty Sark (for Maritime Greenwich) DLR Station",
        "type": "Information",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLCUT",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHROW",
        "fromDate": "2023-10-01T04:00:00Z",
        "toDate": "2024-06-30T22:00:00Z",
        "description": "Harrow & Wealdstone: Until early June 2024, the car park adjacent to Ellen Webb Drive at Harrow & Wealdstone will be closed.",
        "commonName": "Harrow & Wealdstone Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GHROW",
        "appearance": "Information"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUTBC",
        "fromDate": "2023-10-22T22:33:00Z",
        "toDate": "2024-02-29T01:29:00Z",
        "description": "Tooting Bec: reduced escalator service - there is no down escalator from the ticket hall until late February 2024 due to planned maintenance.",
        "commonName": "Tooting Bec Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUTBC",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUVIC",
        "fromDate": "2023-12-01T16:38:00Z",
        "toDate": "2023-12-30T01:29:00Z",
        "description": "VICTORIA UNDERGROUND STATION: Until Friday 29 December, the Terminus Place entrance is closed due to construction works. Please use the entrance in Victoria Street instead.",
        "commonName": "Victoria Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUVIC",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUVIC",
        "fromDate": "2023-12-01T16:40:00Z",
        "toDate": "2023-12-30T01:29:00Z",
        "description": "VICTORIA UNDERGROUND STATION: Until Friday 29 December, the Terminus Place entrance is closed due to construction works. Please use the entrance in Victoria Street instead.",
        "commonName": "Victoria Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUVIC",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUSEA",
        "fromDate": "2023-12-13T03:30:00Z",
        "toDate": "2024-01-23T01:29:00Z",
        "description": "South Ealing: From Wednesday 13 December until Monday 22 January, the eastbound platform at South Ealing will be closed for planned platform works. Westbound trains are not affected and will serve the station as usual during these works.",
        "commonName": "South Ealing Underground Station",
        "type": "Closure",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUSEA",
        "appearance": "PlannedWork",
        "additionalInformation": "To travel eastbound from South Ealing: Use an westbound train to Northfields and change there for an eastbound service. Alternatively, use Northfields station which is a short walk away via Bramley Road. To travel eastbound to South Ealing: Continue to Acton Town and change for a we stbound service. Alternativley walk via Bramley Road"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUBMY",
        "fromDate": "2023-12-05T13:08:00Z",
        "toDate": "2024-06-20T00:29:00Z",
        "description": "BERMONDSEY STATION: No step-free access lift service available until mid June 2024 due to planned maintenance works.",
        "commonName": "Bermondsey Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUBMY",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUBMY",
        "fromDate": "2023-12-05T13:10:00Z",
        "toDate": "2024-06-20T00:29:00Z",
        "description": "BERMONDSEY STATION: No step-free access lift service available until mid June 2024 due to planned maintenance works",
        "commonName": "Bermondsey Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUBMY",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUSGT",
        "fromDate": "2023-12-09T00:02:00Z",
        "toDate": "2023-12-16T01:29:00Z",
        "description": "Southgate: reduced escalator service - no down escalator due to a fault.",
        "commonName": "Southgate Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUSGT",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUPAC",
        "fromDate": "2023-12-06T23:59:00Z",
        "toDate": "2023-12-16T01:29:00Z",
        "description": "Paddington: reduced escalator service - no down escalator from National Rail station to London Underground station due to a fault.",
        "commonName": "Paddington Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUPAC",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GMDNHEAD",
        "fromDate": "2023-11-06T04:30:00Z",
        "toDate": "2024-09-01T00:29:00Z",
        "description": "MAIDENHEAD STATION: From Monday 6 November until August 2024, no step-free access between street level and platforms 2 and 3. This will affect westbound Elizabeth line and GWR services as well as some eastbound services during service disruption and engineering works. Marlow services would not be affected at any time.",
        "commonName": "Maidenhead Rail Station",
        "type": "Interchange Message",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GMDNHEAD",
        "appearance": "PlannedWork"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUBMY",
        "fromDate": "2023-12-05T02:06:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Bermondsey: No Step Free Access - Step free access is not available due to planned maintenance. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Bermondsey Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUBMY",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GCLDNNRB",
        "fromDate": "2023-12-12T08:24:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Caledonian Road & Barnsbury: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Caledonian Road & Barnsbury Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GCLDNNRB",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLDEP",
        "fromDate": "2023-12-12T17:36:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Deptford Bridge: No Step Free Access - Step free access is not available for trains towards Lewisham due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Deptford Bridge DLR Station",
        "type": "Interchange Message",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLDEP",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GEDMNGRN",
        "fromDate": "2023-12-05T02:09:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Edmonton Green: No Step Free Access - Step free access is not available to the northbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Edmonton Green Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GEDMNGRN",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHAKNYNM",
        "fromDate": "2023-12-11T00:04:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hackney Downs: No Step Free Access - The lifts will be out of order between platfrom 1 and the interchange for Hackney Central and the exit from now until further notice at Hackney Downs station.",
        "commonName": "Hackney Downs Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GHAKNYNM",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUBBN",
        "fromDate": "2023-12-13T00:14:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Barbican: No Step Free Access - Step free access is not available between the westbound platform at Barbican and the Elizabeth line at Farringdon due to unavailability of staff. Call 0343 222 1234 if you need help planning your journey.",
        "commonName": "Barbican Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUBBN",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHAKNYNM",
        "fromDate": "2023-12-10T11:11:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hackney Downs: No Step Free Access - Step free access is not available between Hackney Downs (platform 1 towards Liverpool Street) and Hackney Central due to a faulty lift. Call us on 0343 222 1234 for further help.",
        "commonName": "Hackney Downs Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GHAKNYNM",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHMPSTDH",
        "fromDate": "2023-12-05T02:12:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hampstead Heath: No Step Free Access - Step free access is not available to the westbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Hampstead Heath Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GHMPSTDH",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUHWE",
        "fromDate": "2023-12-10T16:06:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hounslow East: No Step Free Access - Step free access is not available to the eastbound platform due to planned works. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Hounslow East Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUHWE",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GKENR",
        "fromDate": "2023-12-09T09:54:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Kensal Rise: No Step Free Access - Step free access is not available to the eastbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Kensal Rise Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GKENR",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLKGV",
        "fromDate": "2023-12-12T00:28:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "King George V: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "King George V DLR Station",
        "type": "Interchange Message",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLKGV",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GNEWXGTE",
        "fromDate": "2023-12-05T02:19:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "New Cross Gate: No Step Free Access - Step free access is not available to platforms 1 and 2 towards West Croydon, Crystal Palace, Victoria, Sutton and Caterham due to a faulty lift. Call us on 0343 222 1234 if you need further information.",
        "commonName": "New Cross Gate Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GNEWXGTE",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GTWYFORD",
        "fromDate": "2023-12-05T14:24:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Twyford: No Step Free Access - Step free access is not available due to platform 4 (trains towards Paddington) due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Twyford Rail Station",
        "type": "Interchange Message",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GTWYFORD",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUVIC",
        "fromDate": "2023-12-12T01:58:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Victoria: No Step Free Access - Step free access is not available between the National Rail station and the westbound District and Circle line platform. For step free access to all other Underground platforms, use the entrance on Cardinal Place.",
        "commonName": "Victoria Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUVIC",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GWHHRTLA",
        "fromDate": "2023-12-05T02:23:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "White Hart Lane: No Step Free Access - Step free access is not available to the southbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "White Hart Lane Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GWHHRTLA",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLWLA",
        "fromDate": "2023-12-11T09:28:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Woolwich Arsenal: No Step Free Access - Step free access is not available to the eastbound Southeastern platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Woolwich Arsenal DLR Station",
        "type": "Interchange Message",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLWLA",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLDEP",
        "fromDate": "2023-12-13T00:22:53Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Deptford Bridge: No Step Free Access - Step free access is not available for trains towards Lewisham due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Deptford Bridge DLR Station",
        "type": "Information",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLDEP",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GEDMNGRN",
        "fromDate": "2023-12-13T00:22:56Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Edmonton Green: No Step Free Access - Step free access is not available to the northbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Edmonton Green Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GEDMNGRN",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHAKNYNM",
        "fromDate": "2023-12-13T00:23:01Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hackney Downs: No Step Free Access - The lifts will be out of order between platfrom 1 and the interchange for Hackney Central and the exit from now until further notice at Hackney Downs station.",
        "commonName": "Hackney Downs Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GHAKNYNM",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHMPSTDH",
        "fromDate": "2023-12-13T00:23:04Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hampstead Heath: No Step Free Access - Step free access is not available to the westbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Hampstead Heath Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GHMPSTDH",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUHWE",
        "fromDate": "2023-12-13T00:23:15Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hounslow East: No Step Free Access - Step free access is not available to the eastbound platform due to planned works. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Hounslow East Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUHWE",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GKENR",
        "fromDate": "2023-12-13T00:23:25Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Kensal Rise: No Step Free Access - Step free access is not available to the eastbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Kensal Rise Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GKENR",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUKSH",
        "fromDate": "2023-12-13T00:23:31Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Kentish Town: Closed - Kentish Town Underground station is closed until mid 2024, while escalators are replaced. The National Rail (Thameslink) station remains open. ",
        "commonName": "Kentish Town Underground Station",
        "type": "Closure",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUKSH",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLKGV",
        "fromDate": "2023-12-13T00:23:36Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "King George V: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "King George V DLR Station",
        "type": "Information",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLKGV",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUBMY",
        "fromDate": "2023-12-13T00:22:47Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Bermondsey: No Step Free Access - Step free access is not available due to planned maintenance. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Bermondsey Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUBMY",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GCLDNNRB",
        "fromDate": "2023-12-13T00:22:50Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Caledonian Road & Barnsbury: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n\r\n",
        "commonName": "Caledonian Road & Barnsbury Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GCLDNNRB",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GNEWXGTE",
        "fromDate": "2023-12-13T00:23:58Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "New Cross Gate: No Step Free Access - Step free access is not available to platforms 1 and 2 towards West Croydon, Crystal Palace, Victoria, Sutton and Caterham due to a faulty lift. Call us on 0343 222 1234 if you need further information.\r\n",
        "commonName": "New Cross Gate Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GNEWXGTE",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GTWYFORD",
        "fromDate": "2023-12-13T00:24:17Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Twyford: No Step Free Access - Step free access is not available due to platform 4 (trains towards Paddington) due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Twyford Rail Station",
        "type": "Information",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GTWYFORD",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUVIC",
        "fromDate": "2023-12-13T00:24:25Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Victoria: No Step Free Access - Step free access is not available between the National Rail station and the westbound District and Circle line platform. For step free access to all other Underground platforms, use the entrance on Cardinal Place.\r\n",
        "commonName": "Victoria Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUVIC",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GWHHRTLA",
        "fromDate": "2023-12-13T00:24:29Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "White Hart Lane: No Step Free Access - Step free access is not available to the southbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "White Hart Lane Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GWHHRTLA",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZDLWLA",
        "fromDate": "2023-12-13T00:24:33Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Woolwich Arsenal: No Step Free Access - Step free access is not available to the eastbound Southeastern platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Woolwich Arsenal DLR Station",
        "type": "Information",
        "mode": "dlr",
        "stationAtcoCode": "940GZZDLWLA",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUSEA",
        "fromDate": "2023-12-13T05:03:47Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "South Ealing: Part Closed - From Wednesday 13th December for approximately six weeks the eastbound platform at South Ealing will be closed for planned platform works. westbound trains are not affected and will serve the station as usual.",
        "commonName": "South Ealing Underground Station",
        "type": "Closure",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUSEA",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GBONDST",
        "fromDate": "2023-12-13T05:29:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Bond Street: No Step Free Access - Step free access is not available to/from the Marylebone Lane entrance due unavailability of staff. Use the entrance on Davies Street or Hanover Square instead. Call 0343 222 1234 for help planning your journey.",
        "commonName": "Bond Street",
        "type": "Interchange Message",
        "mode": "elizabeth-line",
        "stationAtcoCode": "910GBONDST",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUOAK",
        "fromDate": "2023-12-13T10:37:48Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Oakwood: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Oakwood Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUOAK",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHACKNYC",
        "fromDate": "2023-12-13T13:48:43Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hackney Central: No Step Free Access - Step free access is not available to the westbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Hackney Central Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GHACKNYC",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GPCKHMQD",
        "fromDate": "2023-12-13T13:53:27Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Queens Road Peckham: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Queens Road Peckham Rail Station",
        "type": "Information",
        "mode": "overground",
        "stationAtcoCode": "910GPCKHMQD",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GHACKNYC",
        "fromDate": "2023-12-13T13:50:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Hackney Central: No Step Free Access - Step free access is not available to the westbound platform due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Hackney Central Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GHACKNYC",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "910GPCKHMQD",
        "fromDate": "2023-12-13T13:54:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Queens Road Peckham: No Step Free Access - Step free access is not available due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Queens Road Peckham Rail Station",
        "type": "Interchange Message",
        "mode": "overground",
        "stationAtcoCode": "910GPCKHMQD",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUGPK",
        "fromDate": "2023-12-13T14:04:35Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Green Park: No Step Free Access - Step free access is not available to the Jubilee line due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.\r\n",
        "commonName": "Green Park Underground Station",
        "type": "Information",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUGPK",
        "appearance": "RealTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.DisruptedPoint, Tfl.Api.Presentation.Entities",
        "atcoCode": "940GZZLUGPK",
        "fromDate": "2023-12-13T14:06:00Z",
        "toDate": "2023-12-14T01:29:00Z",
        "description": "Green Park: No Step Free Access - Step free access is not available to the Jubilee line due to a faulty lift. Call us on 0343 222 1234 if you need help planning your journey.",
        "commonName": "Green Park Underground Station",
        "type": "Interchange Message",
        "mode": "tube",
        "stationAtcoCode": "940GZZLUGPK",
        "appearance": "RealTime"
    }
]
"""#
