included:
  - TubeService
  - Packages
  - TubeServiceTests
  - TubeServiceUITests

excluded:
  - TubeServiceUITests/SnapshotHelper.swift
  - Packages/Models/Sources/Models/Stubs
  - Packages/Models/Sources/Models/Extensions/StationsJSON.swift
  
disabled_rules:
#  - type_name
  - xctfail_message
  - trailing_whitespace
  - trailing_comma
#  - unhandled_throwing_task
  - redundant_string_enum_value

vertical_whitespace:
    max_empty_lines: 2

line_length:
    warning: 180
    ignores_urls: true
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true

file_length:
    ignore_comment_only_lines: true

nesting:
    type_level: 4

#opt_in_rules:
#  - array_init
#  - attributes
#  - closure_end_indentation
#  - closure_spacing
#  - collection_alignment
#  - colon
#  - convenience_type
#  - discarded_notification_center_observer
#  - discouraged_object_literal
#  - empty_collection_literal
#  - empty_count
#  - empty_string
#  - enum_case_associated_values_count
#  - explicit_init
#  - file_name
#  - file_length
#  - fatal_error_message
#  - first_where
#  - modifier_order
#  - force_unwrapping
#  - implicitly_unwrapped_optional
#  - last_where
#  - legacy_random
#  - literal_expression_end_indentation
#  - multiline_arguments
#  - multiline_function_chains
#  - multiline_literal_brackets
#  - multiline_parameters
#  - notification_center_detachment
#  - operator_usage_whitespace
#  - orphaned_doc_comment
#  - overridden_super_call
#  - pattern_matching_keywords
#  - prefer_self_type_over_type_of_self
#  - redundant_nil_coalescing
#  - redundant_type_annotation
#  - strict_fileprivate
#  - todo
#  - toggle_bool
#  - trailing_closure
#  - unneeded_parentheses_in_closure_argument
#  - unused_capture_list
#  - unused_import
#  - vertical_space_between_nested_types
#  - yoda_condition
##
#multiline_arguments:
#  first_argument_location: sameLine
#  only_enforce_after_first_closure_on_first_line: true
#
#private_over_fileprivate:
#  validate_extensions: true
#
#trailing_whitespace:
#  ignores_empty_lines: true
#  ignores_comments: true
#  severity: error
#
#vertical_whitespace:
#  max_empty_lines: 2
#  severity: error
#
#custom_rules:
#  array_constructor:
#    name: "Array/Dictionary initializer"
#    regex: '[let,var] .+ = (\[.+\]\(\))'
#    capture_group: 1
#    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
#    severity: warning
#
#force_cast: error
#force_try: error
#function_body_length:
#    warning: 60
#    error: 100
#
#file_length:
#  warning: 400
#  error: 600
#
#legacy_hashing: error
#
#identifier_name:
#  excluded:
#    - i
#    - id
#    - x
#    - y
#    - z
#
#attributes:
#  always_on_same_line:
#    - "@IBSegueAction"
#    - "@IBAction"
#    - "@NSManaged"
#    - "@objc"
#
#implicitly_unwrapped_optional:
#    severity:
#        error

