xcode_scheme: TubeService
xcode_configuration: Adhoc
output_name: TubeService

export_options: {}
export_method: ad-hoc

match_type: adhoc  # adhoc, app-store (don't need "development", use automatic provisioning for development)
match_git_url: git@github.com:ridgeview-apps/ridgeview-certs.git
match_force_for_new_devices: true
match_type: adhoc

unit_test_devices:
  - iPhone X
  - iPad Air

app_center_owner_name: RidgeviewApps
app_center_owner_type: organization
app_center_app_name: TubeService
app_center_notify_testers: true

upload_to_appcenter: false
upload_to_testflight: false