let elizabethLineArrivalsJSON =
"""
[
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "scheduledTimeOfArrival": "2025-11-07T18:59:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:00:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:17:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:17:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:18:00Z",
        "minutesAndSecondsToArrival": "13:17",
        "minutesAndSecondsToDeparture": "14:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:31:55Z",
        "scheduledTimeOfArrival": "2025-11-07T19:29:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:32:55Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:30:00Z",
        "minutesAndSecondsToArrival": "28:12",
        "minutesAndSecondsToDeparture": "29:12",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:47:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:47:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:48:00Z",
        "minutesAndSecondsToArrival": "43:17",
        "minutesAndSecondsToDeparture": "44:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:02:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:03:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:03:00Z",
        "minutesAndSecondsToArrival": "58:17",
        "minutesAndSecondsToDeparture": "59:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:17:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:17:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:18:00Z",
        "minutesAndSecondsToArrival": "73:17",
        "minutesAndSecondsToDeparture": "74:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:32:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:33:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:33:00Z",
        "minutesAndSecondsToArrival": "88:17",
        "minutesAndSecondsToDeparture": "89:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:47:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:47:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:48:00Z",
        "minutesAndSecondsToArrival": "103:17",
        "minutesAndSecondsToDeparture": "104:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "scheduledTimeOfArrival": "2025-11-07T19:23:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:24:00Z",
        "minutesAndSecondsToArrival": "19:17",
        "minutesAndSecondsToDeparture": "20:17",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:55:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:55:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:56:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:56:00Z",
        "minutesAndSecondsToArrival": "51:17",
        "minutesAndSecondsToDeparture": "52:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:25:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:25:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:26:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:26:00Z",
        "minutesAndSecondsToArrival": "81:17",
        "minutesAndSecondsToDeparture": "82:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:55:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:55:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:56:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:56:00Z",
        "minutesAndSecondsToArrival": "111:17",
        "minutesAndSecondsToDeparture": "112:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:12:35Z",
        "scheduledTimeOfArrival": "2025-11-07T19:11:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:13:35Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:12:00Z",
        "minutesAndSecondsToArrival": "8:52",
        "minutesAndSecondsToDeparture": "9:52",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:41:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:41:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:42:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:42:00Z",
        "minutesAndSecondsToArrival": "37:17",
        "minutesAndSecondsToDeparture": "38:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:10:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:11:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:11:00Z",
        "minutesAndSecondsToArrival": "66:17",
        "minutesAndSecondsToDeparture": "67:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:40:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:40:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:41:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:41:00Z",
        "minutesAndSecondsToArrival": "96:17",
        "minutesAndSecondsToDeparture": "97:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:26:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:26:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:27:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:27:00Z",
        "minutesAndSecondsToArrival": "22:17",
        "minutesAndSecondsToDeparture": "23:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:59:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:59:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:00:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:00:00Z",
        "minutesAndSecondsToArrival": "55:17",
        "minutesAndSecondsToDeparture": "56:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:29:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:29:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:30:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:30:00Z",
        "minutesAndSecondsToArrival": "85:17",
        "minutesAndSecondsToDeparture": "86:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:59:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:59:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T21:00:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T21:00:00Z",
        "minutesAndSecondsToArrival": "115:17",
        "minutesAndSecondsToDeparture": "116:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "scheduledTimeOfArrival": "2025-11-07T18:56:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:03:20Z",
        "scheduledTimeOfDeparture": "2025-11-07T18:56:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "cause": "This service has been delayed by a late running freight train",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:12:21Z",
        "scheduledTimeOfArrival": "2025-11-07T19:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:12:51Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:02:00Z",
        "minutesAndSecondsToArrival": "8:38",
        "minutesAndSecondsToDeparture": "9:8",
        "cause": "This service has been delayed by a late running train being in front of this one",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:13:55Z",
        "scheduledTimeOfArrival": "2025-11-07T19:08:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:14:25Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:08:00Z",
        "minutesAndSecondsToArrival": "10:12",
        "minutesAndSecondsToDeparture": "10:42",
        "cause": "This service has been delayed by a late running freight train",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:14:01Z",
        "scheduledTimeOfArrival": "2025-11-07T19:14:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:14:31Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:14:00Z",
        "minutesAndSecondsToArrival": "10:18",
        "minutesAndSecondsToDeparture": "10:48",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:20:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:20:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:20:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:20:00Z",
        "minutesAndSecondsToArrival": "16:17",
        "minutesAndSecondsToDeparture": "16:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:26:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:26:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:26:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:26:00Z",
        "minutesAndSecondsToArrival": "22:17",
        "minutesAndSecondsToDeparture": "22:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:32:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:32:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:32:00Z",
        "minutesAndSecondsToArrival": "28:17",
        "minutesAndSecondsToDeparture": "28:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:39:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:39:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:39:00Z",
        "minutesAndSecondsToArrival": "35:17",
        "minutesAndSecondsToDeparture": "35:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:46:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:46:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:46:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:46:00Z",
        "minutesAndSecondsToArrival": "42:17",
        "minutesAndSecondsToDeparture": "42:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:54:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:54:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:54:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:54:00Z",
        "minutesAndSecondsToArrival": "50:17",
        "minutesAndSecondsToDeparture": "50:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:01:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:01:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:01:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:01:00Z",
        "minutesAndSecondsToArrival": "57:17",
        "minutesAndSecondsToDeparture": "57:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:09:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:09:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:09:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:09:00Z",
        "minutesAndSecondsToArrival": "65:17",
        "minutesAndSecondsToDeparture": "65:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:16:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:16:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:16:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:16:00Z",
        "minutesAndSecondsToArrival": "72:17",
        "minutesAndSecondsToDeparture": "72:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:24:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:24:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:24:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:24:00Z",
        "minutesAndSecondsToArrival": "80:17",
        "minutesAndSecondsToDeparture": "80:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:31:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:31:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:31:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:31:00Z",
        "minutesAndSecondsToArrival": "87:17",
        "minutesAndSecondsToDeparture": "87:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:39:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:39:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:39:00Z",
        "minutesAndSecondsToArrival": "95:17",
        "minutesAndSecondsToDeparture": "95:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:46:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:46:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:46:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:46:00Z",
        "minutesAndSecondsToArrival": "102:17",
        "minutesAndSecondsToDeparture": "102:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:54:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:54:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:54:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:54:00Z",
        "minutesAndSecondsToArrival": "110:17",
        "minutesAndSecondsToDeparture": "110:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T21:01:00Z",
        "scheduledTimeOfArrival": "2025-11-07T21:01:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T21:01:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T21:01:00Z",
        "minutesAndSecondsToArrival": "117:17",
        "minutesAndSecondsToDeparture": "117:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:05:43Z",
        "scheduledTimeOfArrival": "2025-11-07T18:59:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:06:13Z",
        "scheduledTimeOfDeparture": "2025-11-07T18:59:00Z",
        "minutesAndSecondsToArrival": "2:0",
        "minutesAndSecondsToDeparture": "2:30",
        "cause": "This service has been delayed by a late running train being in front of this one",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "scheduledTimeOfArrival": "2025-11-07T19:05:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:05:00Z",
        "minutesAndSecondsToArrival": "1:17",
        "minutesAndSecondsToDeparture": "1:17",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:11:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:11:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:11:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:11:00Z",
        "minutesAndSecondsToArrival": "7:17",
        "minutesAndSecondsToDeparture": "7:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:17:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:17:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:17:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:17:00Z",
        "minutesAndSecondsToArrival": "13:17",
        "minutesAndSecondsToDeparture": "13:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:23:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:23:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:23:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:23:00Z",
        "minutesAndSecondsToArrival": "19:17",
        "minutesAndSecondsToDeparture": "19:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:29:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:29:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:29:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:29:00Z",
        "minutesAndSecondsToArrival": "25:17",
        "minutesAndSecondsToDeparture": "25:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:35:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:35:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:35:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:35:00Z",
        "minutesAndSecondsToArrival": "31:17",
        "minutesAndSecondsToDeparture": "31:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:42:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:42:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:42:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:42:00Z",
        "minutesAndSecondsToArrival": "38:17",
        "minutesAndSecondsToDeparture": "38:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:50:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:50:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:50:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:50:00Z",
        "minutesAndSecondsToArrival": "46:17",
        "minutesAndSecondsToDeparture": "46:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:57:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:57:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:57:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:57:00Z",
        "minutesAndSecondsToArrival": "53:17",
        "minutesAndSecondsToDeparture": "53:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:05:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:05:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:07:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:05:00Z",
        "minutesAndSecondsToArrival": "61:17",
        "minutesAndSecondsToDeparture": "63:17",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:12:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:12:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:12:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:12:00Z",
        "minutesAndSecondsToArrival": "68:17",
        "minutesAndSecondsToDeparture": "68:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:20:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:20:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:20:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:20:00Z",
        "minutesAndSecondsToArrival": "76:17",
        "minutesAndSecondsToDeparture": "76:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:27:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:27:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:27:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:27:00Z",
        "minutesAndSecondsToArrival": "83:17",
        "minutesAndSecondsToDeparture": "83:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:35:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:35:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:35:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:35:00Z",
        "minutesAndSecondsToArrival": "91:17",
        "minutesAndSecondsToDeparture": "91:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:42:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:42:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:42:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:42:00Z",
        "minutesAndSecondsToArrival": "98:17",
        "minutesAndSecondsToDeparture": "98:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:50:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:50:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:50:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:50:00Z",
        "minutesAndSecondsToArrival": "106:17",
        "minutesAndSecondsToDeparture": "106:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:57:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:57:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:57:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:57:00Z",
        "minutesAndSecondsToArrival": "113:17",
        "minutesAndSecondsToDeparture": "113:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "scheduledTimeOfArrival": "2025-11-07T19:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:03:42Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:03:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:05:20Z",
        "scheduledTimeOfArrival": "2025-11-07T19:05:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:06:20Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:06:00Z",
        "minutesAndSecondsToArrival": "1:37",
        "minutesAndSecondsToDeparture": "2:37",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:08:09Z",
        "scheduledTimeOfArrival": "2025-11-07T19:08:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:09:09Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:09:00Z",
        "minutesAndSecondsToArrival": "4:26",
        "minutesAndSecondsToDeparture": "5:26",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:14:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:14:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:15:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:15:00Z",
        "minutesAndSecondsToArrival": "10:17",
        "minutesAndSecondsToDeparture": "11:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:20:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:20:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:21:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:21:00Z",
        "minutesAndSecondsToArrival": "16:17",
        "minutesAndSecondsToDeparture": "17:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:32:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:33:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:33:00Z",
        "minutesAndSecondsToArrival": "28:17",
        "minutesAndSecondsToDeparture": "29:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:35:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:35:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:36:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:36:00Z",
        "minutesAndSecondsToArrival": "31:17",
        "minutesAndSecondsToDeparture": "32:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:47:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:38:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:39:00Z",
        "minutesAndSecondsToArrival": "43:17",
        "minutesAndSecondsToDeparture": "44:17",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:44:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:44:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:45:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:45:00Z",
        "minutesAndSecondsToArrival": "40:17",
        "minutesAndSecondsToDeparture": "41:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T19:51:00Z",
        "scheduledTimeOfArrival": "2025-11-07T19:51:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T19:52:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T19:52:00Z",
        "minutesAndSecondsToArrival": "47:17",
        "minutesAndSecondsToDeparture": "48:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:06:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:06:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:07:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:07:00Z",
        "minutesAndSecondsToArrival": "62:17",
        "minutesAndSecondsToDeparture": "63:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:14:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:14:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:15:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:15:00Z",
        "minutesAndSecondsToArrival": "70:17",
        "minutesAndSecondsToDeparture": "71:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:21:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:21:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:22:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:22:00Z",
        "minutesAndSecondsToArrival": "77:17",
        "minutesAndSecondsToDeparture": "78:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:36:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:36:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:37:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:37:00Z",
        "minutesAndSecondsToArrival": "92:17",
        "minutesAndSecondsToDeparture": "93:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:44:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:44:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:45:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:45:00Z",
        "minutesAndSecondsToArrival": "100:17",
        "minutesAndSecondsToDeparture": "101:17",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GTOTCTRD",
        "stationName": "Tottenham Court Road",
        "estimatedTimeOfArrival": "2025-11-07T20:51:00Z",
        "scheduledTimeOfArrival": "2025-11-07T20:51:00Z",
        "estimatedTimeOfDeparture": "2025-11-07T20:52:00Z",
        "scheduledTimeOfDeparture": "2025-11-07T20:52:00Z",
        "minutesAndSecondsToArrival": "107:17",
        "minutesAndSecondsToDeparture": "108:17",
        "departureStatus": "OnTime"
    }
]
"""
