let elizabethLineArrivalsJSON =
"""
[
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:46:15Z",
        "scheduledTimeOfArrival": "2023-09-06T12:46:00Z",
        "estimatedTimeOfDeparture": "2023-09-06T12:47:15Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:47:00Z",
        "minutesAndSecondsToArrival": "6:21",
        "minutesAndSecondsToDeparture": "7:21",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "scheduledTimeOfArrival": "2023-09-06T12:38:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:39:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:53:00Z",
        "scheduledTimeOfArrival": "2023-09-06T12:53:00Z",
        "estimatedTimeOfDeparture": "2023-09-06T12:54:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:54:00Z",
        "minutesAndSecondsToArrival": "13:6",
        "minutesAndSecondsToDeparture": "14:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "scheduledTimeOfArrival": "2023-09-06T12:39:00Z",
        "estimatedTimeOfDeparture": "2023-09-06T12:41:01Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:41:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "1:7",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:47:00Z",
        "scheduledTimeOfArrival": "2023-09-06T12:47:00Z",
        "estimatedTimeOfDeparture": "2023-09-06T12:49:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:49:00Z",
        "minutesAndSecondsToArrival": "7:6",
        "minutesAndSecondsToDeparture": "9:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:54:00Z",
        "scheduledTimeOfArrival": "2023-09-06T12:54:00Z",
        "estimatedTimeOfDeparture": "2023-09-06T12:56:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:56:00Z",
        "minutesAndSecondsToArrival": "14:6",
        "minutesAndSecondsToDeparture": "16:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfDeparture": "2023-09-06T12:45:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:45:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "5:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:51:00Z",
        "scheduledTimeOfArrival": "2023-09-06T12:51:00Z",
        "estimatedTimeOfDeparture": "2023-09-06T12:52:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T12:52:00Z",
        "minutesAndSecondsToArrival": "11:6",
        "minutesAndSecondsToDeparture": "12:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfDeparture": "2023-09-06T13:00:00Z",
        "scheduledTimeOfDeparture": "2023-09-06T13:00:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "20:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:42:00Z",
        "scheduledTimeOfArrival": "2023-09-06T12:42:00Z",
        "minutesAndSecondsToArrival": "2:6",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:50:22Z",
        "scheduledTimeOfArrival": "2023-09-06T12:50:00Z",
        "minutesAndSecondsToArrival": "10:28",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTON",
        "stationName": "London Paddington Rail Station",
        "estimatedTimeOfArrival": "2023-09-06T12:57:00Z",
        "scheduledTimeOfArrival": "2023-09-06T12:57:00Z",
        "minutesAndSecondsToArrival": "17:6",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    }
]
"""
