let elizabethLineArrivalsWithDuplicatesJSON =
"""
[
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:49:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:49:00Z",
        "minutesAndSecondsToArrival": "70:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:49:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:49:00Z",
        "minutesAndSecondsToArrival": "70:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:49:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:49:00Z",
        "minutesAndSecondsToArrival": "70:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 5",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:51:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:51:00Z",
        "minutesAndSecondsToArrival": "72:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 5",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:51:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:51:00Z",
        "minutesAndSecondsToArrival": "72:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 5",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:51:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:51:00Z",
        "minutesAndSecondsToArrival": "72:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:05:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:05:00Z",
        "minutesAndSecondsToArrival": "86:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:05:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:05:00Z",
        "minutesAndSecondsToArrival": "86:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:05:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:05:00Z",
        "minutesAndSecondsToArrival": "86:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 5",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:17:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:17:00Z",
        "minutesAndSecondsToArrival": "98:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 5",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:17:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:17:00Z",
        "minutesAndSecondsToArrival": "98:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 5",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:17:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:17:00Z",
        "minutesAndSecondsToArrival": "98:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 12",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:19:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:19:00Z",
        "minutesAndSecondsToArrival": "100:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 12",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:19:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:19:00Z",
        "minutesAndSecondsToArrival": "100:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 12",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:19:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:19:00Z",
        "minutesAndSecondsToArrival": "100:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:32:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:32:00Z",
        "minutesAndSecondsToArrival": "113:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:32:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:32:00Z",
        "minutesAndSecondsToArrival": "113:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 11",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T23:32:00Z",
        "scheduledTimeOfArrival": "2025-11-02T23:32:00Z",
        "minutesAndSecondsToArrival": "113:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 9",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:19:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:19:00Z",
        "minutesAndSecondsToArrival": "40:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 9",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:19:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:19:00Z",
        "minutesAndSecondsToArrival": "40:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 9",
        "destinationNaptanId": "910GPADTON",
        "destinationName": "London Paddington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:19:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:19:00Z",
        "minutesAndSecondsToArrival": "40:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GGIDEAPK",
        "destinationName": "Gidea Park Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T21:45:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:45:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "6:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GGIDEAPK",
        "destinationName": "Gidea Park Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T21:45:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:45:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "6:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GGIDEAPK",
        "destinationName": "Gidea Park Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T21:45:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:45:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "6:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GGIDEAPK",
        "destinationName": "Gidea Park Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:00:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:00:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "21:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GGIDEAPK",
        "destinationName": "Gidea Park Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:00:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:00:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "21:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GGIDEAPK",
        "destinationName": "Gidea Park Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:00:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:00:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "21:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:06:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:06:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:06:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:06:00Z",
        "minutesAndSecondsToArrival": "27:42",
        "minutesAndSecondsToDeparture": "27:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:06:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:06:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:06:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:06:00Z",
        "minutesAndSecondsToArrival": "27:42",
        "minutesAndSecondsToDeparture": "27:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:06:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:06:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:06:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:06:00Z",
        "minutesAndSecondsToArrival": "27:42",
        "minutesAndSecondsToDeparture": "27:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:30:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:30:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:33:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:33:00Z",
        "minutesAndSecondsToArrival": "51:42",
        "minutesAndSecondsToDeparture": "54:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:30:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:30:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:33:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:33:00Z",
        "minutesAndSecondsToArrival": "51:42",
        "minutesAndSecondsToDeparture": "54:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:30:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:30:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:33:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:33:00Z",
        "minutesAndSecondsToArrival": "51:42",
        "minutesAndSecondsToDeparture": "54:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:57:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:57:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T23:03:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:03:00Z",
        "minutesAndSecondsToArrival": "78:42",
        "minutesAndSecondsToDeparture": "84:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:57:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:57:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T23:03:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:03:00Z",
        "minutesAndSecondsToArrival": "78:42",
        "minutesAndSecondsToDeparture": "84:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:57:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:57:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T23:03:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:03:00Z",
        "minutesAndSecondsToArrival": "78:42",
        "minutesAndSecondsToDeparture": "84:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GHAYESAH",
        "destinationName": "Hayes & Harlington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:35:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:35:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "116:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GHAYESAH",
        "destinationName": "Hayes & Harlington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:35:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:35:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "116:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GHAYESAH",
        "destinationName": "Hayes & Harlington Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:35:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:35:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "116:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:36:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:36:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:36:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:36:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM4",
        "destinationName": "Heathrow Terminal 4 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:36:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:36:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:01:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:01:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:02:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:02:00Z",
        "minutesAndSecondsToArrival": "22:42",
        "minutesAndSecondsToDeparture": "23:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:01:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:01:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:02:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:02:00Z",
        "minutesAndSecondsToArrival": "22:42",
        "minutesAndSecondsToDeparture": "23:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:01:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:01:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:02:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:02:00Z",
        "minutesAndSecondsToArrival": "22:42",
        "minutesAndSecondsToDeparture": "23:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:15:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:15:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "96:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:15:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:15:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "96:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GMDNHEAD",
        "destinationName": "Maidenhead Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:15:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:15:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "96:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:10:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:11:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:11:00Z",
        "minutesAndSecondsToArrival": "31:42",
        "minutesAndSecondsToDeparture": "32:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:10:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:11:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:11:00Z",
        "minutesAndSecondsToArrival": "31:42",
        "minutesAndSecondsToDeparture": "32:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:10:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:11:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:11:00Z",
        "minutesAndSecondsToArrival": "31:42",
        "minutesAndSecondsToDeparture": "32:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:41:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:41:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "62:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:41:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:41:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "62:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:41:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:41:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "62:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:38:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:39:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "0:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:38:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:39:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "0:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GRDNGSTN",
        "destinationName": "Reading Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:38:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:39:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "0:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:15:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:15:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:18:00Z",
        "minutesAndSecondsToArrival": "36:42",
        "minutesAndSecondsToDeparture": "39:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:15:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:15:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:18:00Z",
        "minutesAndSecondsToArrival": "36:42",
        "minutesAndSecondsToDeparture": "39:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:15:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:15:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:18:00Z",
        "minutesAndSecondsToArrival": "36:42",
        "minutesAndSecondsToDeparture": "39:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:42:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:42:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:48:00Z",
        "minutesAndSecondsToArrival": "63:42",
        "minutesAndSecondsToDeparture": "69:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:42:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:42:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:48:00Z",
        "minutesAndSecondsToArrival": "63:42",
        "minutesAndSecondsToDeparture": "69:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:42:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:42:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:48:00Z",
        "minutesAndSecondsToArrival": "63:42",
        "minutesAndSecondsToDeparture": "69:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:18:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "99:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:18:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "99:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T23:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T23:18:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "99:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:46:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:46:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:48:12Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:48:00Z",
        "minutesAndSecondsToArrival": "7:42",
        "minutesAndSecondsToDeparture": "9:54",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:46:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:46:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:48:12Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:48:00Z",
        "minutesAndSecondsToArrival": "7:42",
        "minutesAndSecondsToDeparture": "9:54",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GHTRWTM5",
        "destinationName": "Heathrow Terminal 5 Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:46:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:46:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:48:12Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:48:00Z",
        "minutesAndSecondsToArrival": "7:42",
        "minutesAndSecondsToDeparture": "9:54",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:32:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:34:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:32:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:34:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "scheduledTimeOfArrival": "2025-11-02T21:32:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:34:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:40:30Z",
        "scheduledTimeOfArrival": "2025-11-02T21:39:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:41:30Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:41:00Z",
        "minutesAndSecondsToArrival": "2:12",
        "minutesAndSecondsToDeparture": "3:12",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:40:30Z",
        "scheduledTimeOfArrival": "2025-11-02T21:39:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:41:30Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:41:00Z",
        "minutesAndSecondsToArrival": "2:12",
        "minutesAndSecondsToDeparture": "3:12",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:40:30Z",
        "scheduledTimeOfArrival": "2025-11-02T21:39:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:41:30Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:41:00Z",
        "minutesAndSecondsToArrival": "2:12",
        "minutesAndSecondsToDeparture": "3:12",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:47:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:47:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:49:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:49:00Z",
        "minutesAndSecondsToArrival": "8:42",
        "minutesAndSecondsToDeparture": "10:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:47:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:47:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:49:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:49:00Z",
        "minutesAndSecondsToArrival": "8:42",
        "minutesAndSecondsToDeparture": "10:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:47:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:47:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:49:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:49:00Z",
        "minutesAndSecondsToArrival": "8:42",
        "minutesAndSecondsToDeparture": "10:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:55:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:55:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:56:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:56:00Z",
        "minutesAndSecondsToArrival": "16:42",
        "minutesAndSecondsToDeparture": "17:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:55:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:55:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:56:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:56:00Z",
        "minutesAndSecondsToArrival": "16:42",
        "minutesAndSecondsToDeparture": "17:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:55:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:55:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:56:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:56:00Z",
        "minutesAndSecondsToArrival": "16:42",
        "minutesAndSecondsToDeparture": "17:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:10:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:14:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:14:00Z",
        "minutesAndSecondsToArrival": "31:42",
        "minutesAndSecondsToDeparture": "35:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:10:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:14:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:14:00Z",
        "minutesAndSecondsToArrival": "31:42",
        "minutesAndSecondsToDeparture": "35:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:10:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:10:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:14:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:14:00Z",
        "minutesAndSecondsToArrival": "31:42",
        "minutesAndSecondsToDeparture": "35:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:24:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:24:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:29:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:29:00Z",
        "minutesAndSecondsToArrival": "45:42",
        "minutesAndSecondsToDeparture": "50:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:24:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:24:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:29:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:29:00Z",
        "minutesAndSecondsToArrival": "45:42",
        "minutesAndSecondsToDeparture": "50:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:24:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:24:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:29:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:29:00Z",
        "minutesAndSecondsToArrival": "45:42",
        "minutesAndSecondsToDeparture": "50:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:44:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:44:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "65:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:44:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:44:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "65:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GABWDXR",
        "destinationName": "Abbey Wood",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T22:44:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:44:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "65:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T21:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:37:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "0:42",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T21:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:37:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "0:42",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfDeparture": "2025-11-02T21:39:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:37:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "0:42",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:51:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:51:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:52:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:52:00Z",
        "minutesAndSecondsToArrival": "12:42",
        "minutesAndSecondsToDeparture": "13:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:51:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:51:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:52:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:52:00Z",
        "minutesAndSecondsToArrival": "12:42",
        "minutesAndSecondsToDeparture": "13:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:51:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:51:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T21:52:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T21:52:00Z",
        "minutesAndSecondsToArrival": "12:42",
        "minutesAndSecondsToDeparture": "13:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:02:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:07:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:07:00Z",
        "minutesAndSecondsToArrival": "23:42",
        "minutesAndSecondsToDeparture": "28:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:02:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:07:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:07:00Z",
        "minutesAndSecondsToArrival": "23:42",
        "minutesAndSecondsToDeparture": "28:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:02:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:07:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:07:00Z",
        "minutesAndSecondsToArrival": "23:42",
        "minutesAndSecondsToDeparture": "28:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:21:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:21:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:22:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:22:00Z",
        "minutesAndSecondsToArrival": "42:42",
        "minutesAndSecondsToDeparture": "43:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:21:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:21:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:22:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:22:00Z",
        "minutesAndSecondsToArrival": "42:42",
        "minutesAndSecondsToDeparture": "43:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:21:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:21:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:22:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:22:00Z",
        "minutesAndSecondsToArrival": "42:42",
        "minutesAndSecondsToDeparture": "43:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:32:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:37:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:37:00Z",
        "minutesAndSecondsToArrival": "53:42",
        "minutesAndSecondsToDeparture": "58:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:32:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:37:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:37:00Z",
        "minutesAndSecondsToArrival": "53:42",
        "minutesAndSecondsToDeparture": "58:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform A",
        "destinationNaptanId": "910GSHENFLD",
        "destinationName": "Shenfield Rail Station",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:32:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-02T22:37:00Z",
        "scheduledTimeOfDeparture": "2025-11-02T22:37:00Z",
        "minutesAndSecondsToArrival": "53:42",
        "minutesAndSecondsToDeparture": "58:42",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:52:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:52:00Z",
        "minutesAndSecondsToArrival": "13:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:52:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:52:00Z",
        "minutesAndSecondsToArrival": "13:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:52:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:52:00Z",
        "minutesAndSecondsToArrival": "13:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:53:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:53:00Z",
        "minutesAndSecondsToArrival": "14:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:53:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:53:00Z",
        "minutesAndSecondsToArrival": "14:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:53:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:53:00Z",
        "minutesAndSecondsToArrival": "14:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:59:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:59:00Z",
        "minutesAndSecondsToArrival": "20:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:59:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:59:00Z",
        "minutesAndSecondsToArrival": "20:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:59:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:59:00Z",
        "minutesAndSecondsToArrival": "20:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:22:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:22:00Z",
        "minutesAndSecondsToArrival": "43:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:22:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:22:00Z",
        "minutesAndSecondsToArrival": "43:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:22:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:22:00Z",
        "minutesAndSecondsToArrival": "43:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:25:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:25:00Z",
        "minutesAndSecondsToArrival": "46:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:25:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:25:00Z",
        "minutesAndSecondsToArrival": "46:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:25:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:25:00Z",
        "minutesAndSecondsToArrival": "46:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:37:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:37:00Z",
        "minutesAndSecondsToArrival": "58:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:37:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:37:00Z",
        "minutesAndSecondsToArrival": "58:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:37:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:37:00Z",
        "minutesAndSecondsToArrival": "58:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:52:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:52:00Z",
        "minutesAndSecondsToArrival": "73:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:52:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:52:00Z",
        "minutesAndSecondsToArrival": "73:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T22:52:00Z",
        "scheduledTimeOfArrival": "2025-11-02T22:52:00Z",
        "minutesAndSecondsToArrival": "73:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:44:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:44:00Z",
        "minutesAndSecondsToArrival": "5:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:44:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:44:00Z",
        "minutesAndSecondsToArrival": "5:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform B",
        "destinationNaptanId": "910GPADTLL",
        "destinationName": "Paddington",
        "naptanId": "910GPADTLL",
        "stationName": "Paddington",
        "estimatedTimeOfArrival": "2025-11-02T21:44:00Z",
        "scheduledTimeOfArrival": "2025-11-02T21:44:00Z",
        "minutesAndSecondsToArrival": "5:42",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "OnTime"
    }
]
"""
