let mildmayLineArrivalsJSON =
"""
[
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 1",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "scheduledTimeOfArrival": "2025-11-04T21:18:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:18:00Z",
        "minutesAndSecondsToArrival": "0:6",
        "minutesAndSecondsToDeparture": "0:6",
        "cause": "This service has been cancelled because of a speed restriction over defective track",
        "departureStatus": "Cancelled"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 1",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T21:32:00Z",
        "scheduledTimeOfArrival": "2025-11-04T21:32:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T21:32:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:32:00Z",
        "minutesAndSecondsToArrival": "14:6",
        "minutesAndSecondsToDeparture": "14:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 1",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T21:46:00Z",
        "scheduledTimeOfArrival": "2025-11-04T21:46:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T21:46:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:46:00Z",
        "minutesAndSecondsToArrival": "28:6",
        "minutesAndSecondsToDeparture": "28:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:03:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:03:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:03:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:03:00Z",
        "minutesAndSecondsToArrival": "45:6",
        "minutesAndSecondsToDeparture": "45:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:17:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:17:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:17:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:17:00Z",
        "minutesAndSecondsToArrival": "59:6",
        "minutesAndSecondsToDeparture": "59:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:33:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:33:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:33:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:33:00Z",
        "minutesAndSecondsToArrival": "75:6",
        "minutesAndSecondsToDeparture": "75:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:47:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:47:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:48:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:48:00Z",
        "minutesAndSecondsToArrival": "89:6",
        "minutesAndSecondsToDeparture": "90:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GRICHMND",
        "destinationName": "Richmond (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T23:02:00Z",
        "scheduledTimeOfArrival": "2025-11-04T23:02:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T23:02:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T23:02:00Z",
        "minutesAndSecondsToArrival": "104:6",
        "minutesAndSecondsToDeparture": "104:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 2",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T21:25:05Z",
        "scheduledTimeOfArrival": "2025-11-04T20:58:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T21:26:05Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:01:00Z",
        "minutesAndSecondsToArrival": "7:11",
        "minutesAndSecondsToDeparture": "8:11",
        "cause": "This service has been delayed by a speed restriction over defective track earlier today",
        "departureStatus": "Delayed"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 2",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "scheduledTimeOfArrival": "2025-11-04T21:16:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:17:00Z",
        "minutesAndSecondsToArrival": "",
        "minutesAndSecondsToDeparture": "",
        "departureStatus": "Cancelled"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 2",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T21:28:00Z",
        "scheduledTimeOfArrival": "2025-11-04T21:28:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T21:30:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:30:00Z",
        "minutesAndSecondsToArrival": "10:6",
        "minutesAndSecondsToDeparture": "12:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform 2",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "scheduledTimeOfArrival": "2025-11-04T21:43:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T21:47:00Z",
        "minutesAndSecondsToArrival": "25:6",
        "minutesAndSecondsToDeparture": "29:6",
        "cause": "This service has been cancelled because of a speed restriction over defective track",
        "departureStatus": "Cancelled"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T21:59:00Z",
        "scheduledTimeOfArrival": "2025-11-04T21:59:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:00:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:00:00Z",
        "minutesAndSecondsToArrival": "41:6",
        "minutesAndSecondsToDeparture": "42:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:13:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:13:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:14:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:14:00Z",
        "minutesAndSecondsToArrival": "55:6",
        "minutesAndSecondsToDeparture": "56:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:28:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:28:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:29:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:29:00Z",
        "minutesAndSecondsToArrival": "70:6",
        "minutesAndSecondsToDeparture": "71:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:43:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:43:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:45:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:45:00Z",
        "minutesAndSecondsToArrival": "85:6",
        "minutesAndSecondsToDeparture": "87:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T22:58:00Z",
        "scheduledTimeOfArrival": "2025-11-04T22:58:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T22:59:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T22:59:00Z",
        "minutesAndSecondsToArrival": "100:6",
        "minutesAndSecondsToDeparture": "101:6",
        "departureStatus": "OnTime"
    },
    {
        "$type": "Tfl.Api.Presentation.Entities.ArrivalDeparture, Tfl.Api.Presentation.Entities",
        "platformName": "Platform Unknown",
        "destinationNaptanId": "910GSTFD",
        "destinationName": "Stratford (London) Rail Station",
        "naptanId": "910GACTNCTL",
        "stationName": "Acton Central Rail Station",
        "estimatedTimeOfArrival": "2025-11-04T23:13:00Z",
        "scheduledTimeOfArrival": "2025-11-04T23:13:00Z",
        "estimatedTimeOfDeparture": "2025-11-04T23:15:00Z",
        "scheduledTimeOfDeparture": "2025-11-04T23:15:00Z",
        "minutesAndSecondsToArrival": "115:6",
        "minutesAndSecondsToDeparture": "117:6",
        "departureStatus": "OnTime"
    }
]
"""
