default_platform(:ios)

##################
#
# Tests & Analyse
#
##################

private_lane :xcode_tests do |options|
  scan(
    scheme: options[:scheme],
    configuration: "Debug",
    device: "iPhone 15 Pro"
  )
end

private_lane :read_xcconfig_file do
  path = "../Config/CI/#{ENV["XCODE_CONFIG"]}.xcconfig"
  Xcodeproj::Config.new(path)
end

lane :unit_tests do
  xcode_tests(scheme: "TubeService")
end

lane :ui_tests do
  xcode_tests(scheme: "TubeServiceUITests")
end

lane :add_badge_overlay do
  badge_shield_title = ENV["XCODE_CONFIG"].slice(0, 4)
  badge_shield_date_text = Time.new.strftime("%d.%m.%y")

  add_badge(
    shield: "#{badge_shield_title}-#{badge_shield_date_text}-blue",
    no_badge: true
  )
end

lane :build_and_upload do
  app_store_connect_api_key(duration: 1200) if is_ci

  xcconfig = read_xcconfig_file

  main_target_bundle_id = xcconfig.attributes['MAIN_TARGET_BUNDLE_ID']

  match_app_identifiers = ["#{main_target_bundle_id}"]

  match(
    readonly: false,
    clone_branch_directly: true,
    git_url: "git@github.com:ridgeview-apps/ridgeview-certs.git",
    app_identifier: match_app_identifiers,
    username: "ci.ridgeview@gmail.com",
    type: "appstore"
  )
  
  increment_build_number(build_number: ENV["BITRISE_BUILD_NUMBER"]) if is_ci

  gym(
    clean: true,
    scheme: "TubeService",
    configuration: "Release",
    xcconfig: "./Config/CI/#{ENV["XCODE_CONFIG"]}.xcconfig",
    export_method: "app-store"
  )

  upload_to_testflight(
    skip_waiting_for_build_processing: true
  )
end