devices([
    "iPhone 17 Pro Max",
    # "iPhone 8 Plus",
    # "iPad Pro (12.9-inch) (6th generation)",
    "iPad Pro 13-inch (M4)"
])

languages([
  "en-GB"
])

clear_previous_screenshots(true)
override_status_bar(true)
# erase_simulator(true)