name: Beta

on:
  push:
    branches:
      - main

env:
  XCODE_CONFIG: Beta
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  MATCH_GIT_BASIC_AUTHORIZATION_BASE64: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_BASE64 }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-deploy-beta:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      - name: Install dependencies
        run: |
          brew install git-secret
          brew install librsvg
          brew install imagemagick
          brew install swiftlint
      - name: Git secret
        run: |
          echo "🔓 Unlocking secrets..."
          echo -n "$GPG_PRIVATE_KEY" | base64 --decode | gpg --import
          git secret reveal
      - name: Fastlane commands
        run: |
          bundle install
          bundle update fastlane
          # bundle exec fastlane unit_tests
          bundle exec fastlane add_badge_overlay
          bundle exec fastlane build
          bundle exec fastlane distribute