name: Beta release

on:
  push:
    branches:
      - main

env:
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  MATCH_GIT_BASIC_AUTHORIZATION_BASE64: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_BASE64 }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  build-and-deploy-beta:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Select Xcode 16.0
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      - name: Install dependencies
        run: |
          brew install librsvg
          brew install imagemagick
          brew install swiftlint
      - name: Run beta
        run: ./Scripts/ci-beta-to-testflight.sh