name: Prod

on:
  push:
    branches:
      - 'release/**'

env:
  XCODE_CONFIG: Prod
  DISTRIBUTION_GROUPS: 'Beta Testers'
  TFL_API_APP_KEY: ${{ secrets.TFL_API_APP_KEY }}
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  MATCH_GIT_BASIC_AUTHORIZATION_BASE64: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_BASE64 }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-deploy-prod:
    runs-on: macos-26
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.5.app
      - name: Confirm Xcode version
        run: xcodebuild -version
      - name: Fastlane commands
        run: |
          bundle install
          bundle update fastlane
          # bundle exec fastlane unit_tests
          bundle exec fastlane build
          bundle exec fastlane distribute


  # Manual approval job
  submit-for-review:
    runs-on: macos-latest
    needs: build-and-deploy-prod
    environment:
      name: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Fastlane commands
        run: |
          echo "Submitting app for review"
          bundle install
          bundle update fastlane
          bundle exec fastlane submit_for_review